### ISSUE TITLE
Outdated blog links

### ISSUE THREAD

**Issue by soulofmischief** [MaxHalford/procedural-art#3]
Blog links are outdated, i.e.
https://maxhalford.github.io/blog/grid-paintings-%C3%A0-la-mondrian-with-javascript/
should be 
https://maxhalford.github.io/blog/mondrian/

**Comment by MaxHalford** [comment]
Hello. Where exactly do you see that first link, the grid-paintings one?

**Comment by MaxHalford** [comment]
Hello and thank you for spotting these broken links. I just fixed them.
